### ISSUE TITLE
Fix-It Issues

### ISSUE THREAD

**Issue by sl0wc0der** [omar2535/encrypted-secure-fs#53]
The reports for reference are available here : https://canvas.sfu.ca/courses/74693/pages/bibifi

For each issue, please create a different pull request and add the PRs as comments under this issue.

1. Inputting directory for keyfile name will cause error (example input: ./fileserver .) (G2 pg13)
2. Any user can add new users and it’s not limited to admin users. (G2 pg13)
3. Memory leaks when decrypting the content. The cleanup of the private RSA key and
plaintext character array is not done when the decryption process passes or fails (G1 pg4)
4. sha256 can be broken using rainbow tables especially on common usernames and filenames with known sha256. Improve this using a securely generated salt or change to using AES for encryption. (G1 pg5)

**Comment by omar2535** [comment]
https://github.com/omar2535/encrypted-secure-fs/pull/58 addresses point `2`

**Comment by omar2535** [comment]
https://github.com/omar2535/encrypted-secure-fs/pull/59 addresses point `1`

**Comment by omar2535** [comment]
https://github.com/omar2535/encrypted-secure-fs/pull/60 addresses point `4`

**Comment by omar2535** [comment]
https://github.com/omar2535/encrypted-secure-fs/pull/61 addresses point `3`

**Comment by omar2535** [comment]
@sl0wc0der Issue completed. Close when verified!

**Comment by sl0wc0der** [comment]
GG
